### ISSUE TITLE
Issue with github action

### ISSUE THREAD

**Issue by NitinKeshavB** [zzstoatzz/prefect-monorepo#1]
pipelines fails stating "When not using an interactive terminal, you must supply a `--key` and 
`--workspace`."

i am running both commands in github actions.

  prefect cloud login --key XXXXXXXXXXXXXXXXXX
  prefect cloud workspace set --workspace XXXXXXXXXXXXX

**Comment by zzstoatzz** [comment]
hi @NitinKeshavB - you don't need to do `prefect cloud login --key ...` if you put the API key in the `env` as I have in my example, all `prefect` commands can find the api key in the env

do you have the whole traceback so we can see why this failed though? you might need to put `--no-prompt` before your command like `prefect --no-prompt [command]`

**Comment by NitinKeshavB** [comment]
@zzstoatzz  - Thanks! for coming back on this. i was able to clear this issue using below steps.

      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: "XXXXXXXX"
          prefect-workspace: "abcd/dev"

but :( ran into one more and it always says as below when i run prefect --no-prompt deploy -n "arthur"
morevoer i am able to run this from my local laptop and deploy to prefect cloud without any trouble.

i even have a prefect.yaml with deployment steps mentioned in it. really need this help here.


logs:
Run PREFECT_VERSION=$(prefect --version)
  PREFECT_VERSION=$(prefect --version)
  PREFECT_SHORT_VERSION="$(cut -d "." -f 2 <<< "$PREFECT_VERSION")"."$(cut -d "." -f 3 <<< "$PREFECT_VERSION")"
  if [ $(echo $PREFECT_SHORT_VERSION'<'10.6 | bc -l) -eq 1 ];
  then
    echo "The currently installed Prefect version (2.$PREFECT_SHORT_VERSION) is not compatible. Updating to the latest Prefect version..."
    pip install prefect -U "prefect>=2.10.8"
  fi
  IFS=',' read -ra deployment_names <<< "arthur"
  for name in "${deployment_names[@]}"; do
    prefect deploy --name "$name"
  done
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PREFECT_API_KEY: XXXXXXXXXX
    PREFECT_API_URL: https://app.prefect.cloud/account/xxxxxxx/workspace/xxxxxxx](https://github.com/NitinKeshavB/prefect_acr/actions/runs/5831434178/job/15814859378#step:9:128)f
    DEV_WORKSPACE: abcd/dev
    pythonLocation: /opt/hostedtoolcache/Python/3.10.12/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.12/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.12/x64/lib
    files: 
Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
